---
version: '2'
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 55
plugins:
  nodesecurity:
    enabled: true
  structure:
    enabled: true
  duplication:
    enabled: false
